### ISSUE TITLE
关于淘宝数据集的预处理

### ISSUE THREAD

**Issue by ustc-zhu** [zyang-16/STAM#7]
你好，我用代码文件中的预处理文件处理淘宝数据集，发现和你们论文中汇报的统计信息并不一样，想请问一下，你们是怎么处理淘宝数据集的呢？

**Comment by zyang-16** [comment]
非常抱歉，我们服务器重装过（因为很奇葩的原因：被人挖矿了。。。）。数据处理代码没了。

您要是要淘宝的数据，我可以发您一份。你留一下邮箱。

**Comment by ustc-zhu** [comment]
zgq@mail.ustc.edu.cn 谢谢
